# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/_processor_cores/nano-cpu32k/sopc/fpga/xilinx-spartan6/ncpu32k-spartan6/ncpu32k-spartan6.cache/wt [current_project]
set_property parent.project_path E:/_processor_cores/nano-cpu32k/sopc/fpga/xilinx-spartan6/ncpu32k-spartan6/ncpu32k-spartan6.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/_processor_cores/nano-cpu32k/sopc/fpga/xilinx-spartan6/ncpu32k-spartan6/ncpu32k-spartan6.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_config.h
set_property file_type "Verilog Header" [get_files E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_config.h]
read_mem E:/_processor_cores/nano-cpu32k/sopc/fpga/xilinx-spartan6/ncpu32k-spartan6/bootstrap.mem
read_verilog -library xil_defaultlib {
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_cell_dff_l.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_cell_dff_lr.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_ipdu.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_ie_mu.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_ie_lu.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_ie_eu.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_ie_au.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_cell_sdpram_sclk.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_cell_pipebuf.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_cell_dff_r.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_regfile.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_psr.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_ifu.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_ieu.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_idu.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_cell_tdpram_sclk.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_bpu.v
  E:/_processor_cores/nano-cpu32k/sopc/rtl/soc_fifo_asclk.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_tsc.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_i_mmu.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_i_cache.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_irqc.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_d_mmu.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_d_cache.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_core.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k_cell_tdpram_aclkd_sclk.v
  E:/_processor_cores/nano-cpu32k/sopc/rtl/soc_pb_uart.v
  E:/_processor_cores/nano-cpu32k/sopc/rtl/soc_pb_spi_master.v
  E:/_processor_cores/nano-cpu32k/rtl/pb_fb_router/pb_fb_router.v
  E:/_processor_cores/nano-cpu32k/rtl/pb_fb_L2_cache/pb_fb_L2_cache.v
  E:/_processor_cores/nano-cpu32k/rtl/pb_fb_DRAM_ctrl/pb_fb_DRAM_ctrl.v
  E:/_processor_cores/nano-cpu32k/rtl/pb_fb_bootrom/pb_fb_bootrom.v
  E:/_processor_cores/nano-cpu32k/rtl/pb_fb_arbiter/pb_fb_arbiter.v
  E:/_processor_cores/nano-cpu32k/rtl/ncpu32k/ncpu32k.v
  E:/_processor_cores/nano-cpu32k/sopc/rtl/soc_toplevel.v
  E:/_processor_cores/nano-cpu32k/sopc/fpga/xilinx-spartan6/ncpu32k-spartan6/toplevel.v
}
read_ip -quiet e:/_processor_cores/nano-cpu32k/sopc/fpga/xilinx-spartan6/ncpu32k-spartan6/ncpu32k-spartan6.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/_processor_cores/nano-cpu32k/sopc/fpga/xilinx-spartan6/ncpu32k-spartan6/ncpu32k-spartan6.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/_processor_cores/nano-cpu32k/sopc/fpga/xilinx-spartan6/ncpu32k-spartan6/ncpu32k-spartan6.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/_processor_cores/nano-cpu32k/sopc/fpga/xilinx-spartan6/ncpu32k-spartan6/ncpu32k-spartan6.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top toplevel -part xc7vx485tffg1157-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef toplevel.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file toplevel_utilization_synth.rpt -pb toplevel_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
